# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: efb54422bc26408b02419a033cc153f39786332e179469093682efc727cabeb6de19d3cecda1cef3630b7dfae6b031b1eca62cbf50022d77aabc42ae57cc75d3

test:
  secret_key_base: 29849313c36ef322c63537631a1b6d0c8035129e350ad078c55b76d18cbd12b3bcc3007afbf967c55e141c9ddfbf241fd9fa3021a07ba3ae88d5b50778bbdfcb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
